version: '2'
services:
  # delivery-db:
  #   image: postgres:13
  #   environment:
  #     TZ: Asiz/Seoul
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres1234
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #   restart: unless-stopped

  delivery:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: broker:29092
    depends_on:
      - broker